Studentmanagementsystem/Models/AddStudentModel.cs
namespace Studentmanagementsystem.Models
{
    public class AddStudentModel
    {
        public String Name { get; set; }
        public String Email { get; set; }
        public int Percentage { get; set; }
        public DateTime DateOfBirth { get; set; }
        public String Department { get; set; }
    }
}

Studentmanagementsystem/Models/Domain/Student.cs
namespace Studentmanagementsystem.Models.Domain
{
    public class Student
    {
        public Guid Id { get; set; }
        public String Name { get; set; }
        public String Email { get; set; }
        public int Percentage { get; set; }
        public DateTime DateOfBirth { get; set; }
        public String Department { get; set; }
    }
}

Studentmanagementsystem/Models/ErrorViewModel.cs
namespace Studentmanagementsystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Studentmanagementsystem/Models/StudentUpdateModel.cs
namespace Studentmanagementsystem.Models
{
    public class StudentUpdateModel
    {
        public Guid Id { get; set; }
        public String Name { get; set; }
        public String Email { get; set; }
        public int Percentage { get; set; }
        public DateTime DateOfBirth { get; set; }
        public String Department { get; set; }
    }
}

Studentmanagementsystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Studentmanagementsystem.Models;
using System.Diagnostics;

namespace Studentmanagementsystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Studentmanagementsystem/Controllers/StudentInformationController.cs
using Microsoft.AspNetCore.Mvc;
using Studentmanagementsystem.Data;
using Studentmanagementsystem.Models;
using Studentmanagementsystem.Models.Domain;

namespace Studentmanagementsystem.Controllers
{
    public class StudentInformationController : Controller
    {
        private readonly DbStudentContext dbstudentcontext;

        public StudentInformationController(DbStudentContext dbstudentcontext)
        {
            this.dbstudentcontext = dbstudentcontext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            {
                var students = dbstudentcontext.Students.ToList();
                return View(students);

            }
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(AddStudentModel addStudentRequest)
        {
            var student = new Student()
            {
                Id = Guid.NewGuid(),
                Name = addStudentRequest.Name,
                Email = addStudentRequest.Email,
                Percentage = addStudentRequest.Percentage,
                DateOfBirth = addStudentRequest.DateOfBirth,
                Department = addStudentRequest.Department,
            };
            dbstudentcontext.Students.Add(student);
            dbstudentcontext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult View(Guid id)
        {
            {
                var student = dbstudentcontext.Students.FirstOrDefault(e => e.Id == id);
                if (student != null)
                {
                    var viewmodel = new StudentUpdateModel()
                    {
                        Id = student.Id,
                        Name = student.Name,
                        Email = student.Email,
                        Percentage = student.Percentage,
                        DateOfBirth = student.DateOfBirth,
                        Department = student.Department,
                    };
                    return View("View", viewmodel);
                }
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult View(StudentUpdateModel model)
        {
            var student = dbstudentcontext.Students.Find(model.Id);
            if (student != null)
            {
                student.Name = model.Name;
                student.Email = model.Email;
                student.Percentage = model.Percentage;
                student.DateOfBirth = model.DateOfBirth;
                student.Department = model.Department;

                dbstudentcontext.SaveChanges();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }
        [HttpPost]
        public IActionResult Delete(StudentUpdateModel model)
        {
            var student = dbstudentcontext.Students.Find(model.Id);
            if (student != null)
            {
                dbstudentcontext.Students.Remove(student);
                dbstudentcontext.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
}  

Studentmanagementsystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Studentmanagementsystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Studentmanagementsystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Studentmanagementsystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Studentmanagementsystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentInformation" asp-action="Add">Add</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentInformation" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Studentmanagementsystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Studentmanagementsystem/Views/StudentInformation/Add.cshtml
@model Studentmanagementsystem.Models.AddStudentModel
@{

}
<h1>Add Employee</h1>
<form method="post" action="Add">
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email</label>
        <input type="text" class="form-control" asp-for="Email">
    </div>
    <div class="mb-3">
    <label for="" class="form-label">Percentage</label>
    <input type="number" class="form-control" asp-for="Percentage">
    </div>
     <div class="mb-3">
    <label for="" class="form-label">DateOfTime</label>
    <input type="date" class="form-control" asp-for="DateOfBirth">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="Department">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Studentmanagementsystem/Views/StudentInformation/Index.cshtml
@model List<Studentmanagementsystem.Models.Domain.Student>
@{

}
<h1>Students</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Percentaage</th>
            <th>DateofBirth</th>
            <th>Department</th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var student in Model)
        {
            <tr>
                <td>@student.Id</td>
                <td>@student.Name</td>
                <td>@student.Email</td>
                <td>@student.Percentage</td>
                <td>@student.DateOfBirth</td>
                <td>@student.Department</td>
                <td><a href="StudentInformation/View/@student.Id">View</a></td>
            </tr>
        }
    </tbody>
</table>

Studentmanagementsystem/Views/StudentInformation/View.cshtml
@model Studentmanagementsystem.Models.StudentUpdateModel
@{

}
<h1>Update Student</h1>
<form method="post" action="View">
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email</label>
        <input type="text" class="form-control" asp-for="Email">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Percentage</label>
        <input type="number" class="form-control" asp-for="Percentage">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">DateOfBirth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="Department">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="submit" class="btn btn-danger"
    asp-action="Delete"
    asp-controller="StudentInformation">Delete</button>
</form>